# Generated by Django 4.1.7 on 2023-10-22 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_messages_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchats',
            name='fromAva',
        ),
        migrations.RemoveField(
            model_name='userchats',
            name='fromName',
        ),
        migrations.RemoveField(
            model_name='userchats',
            name='yourAva',
        ),
        migrations.RemoveField(
            model_name='userchats',
            name='yourName',
        ),
        migrations.AddField(
            model_name='userchats',
            name='he',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='he', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userchats',
            name='you',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='you', to=settings.AUTH_USER_MODEL),
        ),
    ]
