# Generated by Django 4.1.7 on 2023-05-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_messages_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='fileName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
